import fs from 'node:fs';
import assert from 'node:assert/strict';
import {parseDays} from './dist/app.js';
const data=JSON.parse(fs.readFileSync('dist/snapshot.json','utf8'));
const fixture=Array.from({length:13},()=>[]);
fixture[2]=['','','日付','9月10日','11日','12日','13日'];
fixture[4]=['','','曜日','木','金','土','日'];
fixture[5]=['','','1限','社2B'];
fixture[11]=['','','7限','','LHR'];
const days=parseDays(fixture);
assert.equal(days.length,4);
assert.equal(days[0].date,'9月10日');
assert.equal(days[1].date,'9月11日');
assert.equal(days[0].lessons[0].subject,'社2B');
assert.equal(days[1].lessons[6].subject,'LHR');
assert.equal(days[2].lessons.filter(x=>x.subject).length,0);
assert.deepEqual(parseDays([]),[]);
assert.ok(parseDays(data.sheets['時間割']).length>0);
for(const name of ['時間割','連絡']){
 const url=new URL('https://docs.google.com/spreadsheets/d/1H4x9oAtptNot0MAiy-uahZb0Cp6czbAjat3g28bqP98/gviz/tq');
 url.search=new URLSearchParams({sheet:name,headers:'0',tqx:'out:json;responseHandler:verifyCallback',tq:'select *'});
 const response=await fetch(url);assert.equal(response.status,200);
 const text=await response.text();assert.ok(text.includes('verifyCallback('));
 const body=JSON.parse(text.slice(text.indexOf('verifyCallback(')+15,text.lastIndexOf(');')));
 assert.equal(body.status,'ok');assert.ok(body.table.rows.length>5);
 const rows=body.table.rows.map(r=>r.c.map(v=>v?.f??v?.v??''));
 if(name==='時間割')assert.ok(parseDays(rows).length>0);
 console.log(`${name}: live data and callback verified`);
}
console.log('Date parsing, subject mapping, empty days and live feeds passed.');
